stages:
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_VERSION: "1.5.0"
  TF_IN_AUTOMATION: "true"

before_script:
  - echo "Настройка Terraform"
  - terraform --version

# Установка Terraform
install_terraform:
  stage: validate
  script:
    - echo "Установка Terraform версии $TF_VERSION"
    - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip terraform_${TF_VERSION}_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - terraform --version
  cache:
    paths:
      - .terraform/
  only:
    - main
    - develop

# Инициализация Terraform
terraform_init:
  stage: validate
  script:
    - echo "Инициализация Terraform"
    - terraform init
    - terraform validate
  cache:
    paths:
      - .terraform/
  only:
    - main
    - develop

# План инфраструктуры
terraform_plan:
  stage: plan
  script:
    - echo "План инфраструктуры"
    - terraform plan -var-file=terraform/terraform.tfvars -out=tfplan
  artifacts:
    paths:
      - tfplan
    expire_in: 1 week
  only:
    - main
    - develop

# Применение инфраструктуры
terraform_apply:
  stage: apply
  script:
    - echo "Применение инфраструктуры"
    - terraform apply -auto-approve -var-file=terraform/terraform.tfvars
  only:
    - main
  when: manual

# Уничтожение инфраструктуры
terraform_destroy:
  stage: destroy
  script:
    - echo "Уничтожение инфраструктуры"
    - terraform destroy -auto-approve -var-file=terraform/terraform.tfvars
  only:
    - main
  when: manual

# Мониторинг и health check
monitoring:
  stage: apply
  script:
    - echo "Проверка состояния инфраструктуры"
    - terraform output -json > infrastructure.json
    - echo "Инфраструктура развернута успешно"
  only:
    - main
  dependencies:
    - terraform_apply

# Бэкап конфигурации
backup_config:
  stage: apply
  script:
    - echo "Создание бэкапа конфигурации"
    - mkdir -p backups
    - cp terraform/*.tf backups/
    - cp terraform/*.tfvars backups/
    - tar -czf infrastructure-backup-$(date +%Y%m%d-%H%M%S).tar.gz backups/
    - echo "Бэкап создан"
  only:
    - main
  dependencies:
    - terraform_apply