auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# By default, Loki will send anonymous usage data to Grafana Labs.
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_concurrent_tail_requests: 10
  max_entries_limit_per_query: 5000
  max_query_series: 500
  max_query_parallelism: 32
  max_query_lookback: 2160h
  max_query_length: 721h
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  creation_grace_period: 10m
  enforce_metric_name: false
  max_label_names_per_series: 30
  max_label_value_length: 2048
  max_label_name_length: 1024

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

ingester:
  chunk_idle_period: 1h
  chunk_block_size: 262144
  chunk_retain_period: 1m
  max_transfer_retries: 0
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

querier:
  query_timeout: 1m
  tail_max_duration: 1h
  engine:
    timeout: 5m
    max_look_back_period: 30s

frontend:
  compress_responses: true
  max_outstanding_per_tenant: 2048
  log_queries_longer_than: 5s

query_scheduler:
  max_outstanding_requests_per_tenant: 32768
  grpc_client_config:
    max_send_msg_size: 104857600
    max_recv_msg_size: 104857600
    grpc_compression: gzip

distributor:
  ring:
    kvstore:
      store: inmemory
  rate_store:
    max_request_parallelism: 200
    stream_rate_update_interval: 1s

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

analytics:
  reporting_enabled: false