global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@cloud.ru'
  smtp_auth_username: 'alertmanager@cloud.ru'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  email_configs:
  - to: 'admin@cloud.ru'
    subject: 'Cloud.ru Infrastructure Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Status: {{ .Status }}
      Labels: {{ .Labels }}
      {{ end }}
  
  webhook_configs:
  - url: 'http://webhook:5001/'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']