modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      method: GET
      headers:
        Host: localhost
        Accept-Language: en-US
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_body_matches_regexp: []
      fail_if_body_not_matches_regexp: []
      fail_if_header_matches: []
      fail_if_header_not_matches: []
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Content-Type: application/json
      valid_status_codes: [200, 201, 202]

  http_4xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [400, 401, 403, 404, 429]

  http_5xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [500, 502, 503, 504]

  tcp_connect:
    prober: tcp
    timeout: 5s

  postgres:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "J"
      tls: false
      tls_config:
        insecure_skip_verify: false

  redis:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - send: "PING"
          expect: "PONG"

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  dns:
    prober: dns
    timeout: 5s
    dns:
      query_name: "google.com"
      query_type: "A"
      valid_rcodes:
        - NOERROR
      validate_answer_rrs:
        fail_if_matches_regexp: []
        fail_if_not_matches_regexp: []