groups:
  - name: system_alerts
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # High disk usage
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} is down for more than 1 minute"

  - name: database_alerts
    rules:
      # PostgreSQL connection issues
      - alert: PostgreSQLConnectionIssues
        expr: pg_stat_database_numbackends > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of PostgreSQL connections"
          description: "PostgreSQL has more than 80 active connections on {{ $labels.datname }}"

      # PostgreSQL slow queries
      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_database_calls_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of PostgreSQL queries"
          description: "PostgreSQL has more than 100 queries per second on {{ $labels.datname }}"

      # Redis memory usage
      - alert: RedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is above 80% on {{ $labels.instance }}"

      # Redis connected clients
      - alert: RedisConnectedClients
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of Redis connected clients"
          description: "Redis has more than 100 connected clients on {{ $labels.instance }}"

  - name: application_alerts
    rules:
      # High HTTP error rate
      - alert: HighHTTPErrorRate
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP error rate"
          description: "HTTP error rate is above 5% for more than 5 minutes"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP response time"
          description: "95th percentile response time is above 2 seconds for more than 5 minutes"

      # Application crashes
      - alert: ApplicationCrashes
        expr: rate(process_crashes_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Application crashes detected"
          description: "Application has crashed {{ $value }} times in the last 5 minutes"

  - name: infrastructure_alerts
    rules:
      # Load balancer errors
      - alert: LoadBalancerErrors
        expr: rate(lb_http_errors_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High load balancer error rate"
          description: "Load balancer has more than 10 errors per minute"

      # Database connection pool exhausted
      - alert: DatabaseConnectionPoolExhausted
        expr: pg_stat_database_numbackends > 95
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool exhausted"
          description: "Database connection pool is almost exhausted on {{ $labels.datname }}"

      # Redis connection issues
      - alert: RedisConnectionIssues
        expr: redis_connected_clients == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection issues"
          description: "Redis has no connected clients on {{ $labels.instance }}"