groups:
  - name: audio-streaming
    rules:
      - alert: AudioStreamingDown
        expr: up{job="audio-streaming-app"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Audio streaming service is down"
          description: "Audio streaming service has been down for more than 30 seconds"

      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes{name="audio-streaming-app"} / container_spec_memory_limit_bytes{name="audio-streaming-app"}) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% for more than 5 minutes"

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name="audio-streaming-app"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="audio-streaming-app"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1 second for more than 5 minutes"

      - alert: HighErrorRate
        expr: rate(http_requests_total{job="audio-streaming-app",status=~"5.."}[5m]) / rate(http_requests_total{job="audio-streaming-app"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for more than 5 minutes"

      - alert: TooManyConnections
        expr: audio_streaming_active_connections > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many active connections"
          description: "Active connections count is above 1000 for more than 5 minutes"